# Optimasi untuk RAM 16GB & Ryzen 5
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Mempercepat Build
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

# Pengaturan Standar Flutter
android.useAndroidX=true
android.enableJetifier=true

# Paksa Gradle menggunakan cache lokal saja
org.gradle.offline=true